series: GLFW Graphics
title: Normal Mapping
author:
  name: IGME-RIT
  email:
  github: igme-rit
description: This program demonstrates the implementation of normal maps to produce finer lighting details.
language: C++
tags:
  - Graphics
extra_resources:
  - title: OpenGL 4 Shading Language Cookbook (2 ed.), by David Wolff
    link: "https://www.packtpub.com/game-development/opengl-4-shading-language-cookbook-second-edition"
connections:
  - series: GLFW Graphics
    title: Textures
